nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
        allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
        allow_headers: ["Content-Type", "Authorization"]
        expose_headers: ["Link"]
        max_age: 3600
    paths:
        "^/api/":
            allow_credentials: true
            allow_origin: ["http://localhost:3000"]
            allow_headers: ["Content-Type", "Authorization"]
            allow_methods: ["GET", "POST"] #Saqu√© el options :risas:
            max_age: 3600
